color: orange
fieldLayouts:
  b02b5f0e-fa53-42c2-b3f0-52e33aae19d7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-06T08:49:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: acec1dda-f91d-4237-85e4-6c23c10221c5
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d3f54ce2-cda4-40e8-ab3c-572a47d35ed2
        userCondition: null
handle: oya
hasTitleField: true
icon: alien
name: Oya
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
