defaultPlacement: end
enableVersioning: true
entryTypes:
  - 70755e92-2486-4df5-bfa2-b895feecb6af # Oya
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  bfc302a6-a5a7-4e3f-ab9d-0672d31c7915: # TWT
    enabledByDefault: true
    hasUrls: true
    template: homepage/_entry.twig
    uriFormat: 'homepage/{slug}'
type: channel
